vich_uploader:
  db_driver: orm

  metadata:
    type: attribute
    cache: file

  mappings:
    restaurants_banner:
      uri_prefix: /uploads/restaurants/banners
      upload_destination: "%kernel.project_dir%/public/uploads/restaurants/banners"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    users_avatar:
      uri_prefix: /uploads/users/avatars
      upload_destination: "%kernel.project_dir%/public/uploads/users/avatars"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    reviews_image:
      uri_prefix: /uploads/reviews/images
      upload_destination: "%kernel.project_dir%/public/uploads/reviews/images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
