services:
  php:
    container_name: gourmy_php
    networks:
      - default
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: "tail -f /dev/null"
    
  web:
    container_name: gourmy_web
    networks:
      - default
      - global_reverse_proxy
    volumes:
      - ./var:/var/www/html/var
      - ./public/uploads:/var/www/html/public/uploads
    working_dir: /var/www/html
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - php
      - db
    labels:
      caddy: "gourmy.lauralpn.fr"
      caddy.reverse_proxy: "{{upstreams 80}}"

  db:
    container_name: gourmy_db
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    image: postgres:16.3
    environment:

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
  global_reverse_proxy:
    external: true

  
